curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=AIzaSyCPlWLLSB38RGFX55PRfc0d56X4EcSajAs" \
-H 'Content-Type: application/json' \
-X POST \
-d '{
  "contents": [{
    "parts":[{"text": "Quem é o prefeito de Fortaleza?"}]
    }]
   }'